services:
  - type: web
    name: saini-txt-direct
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/nikhilsainiop/Saini-txt-direct
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH;"08e5820769976c0b2a24a54f6fde773e"
        sync: done
      - key: OWNER
        sync: false
      - key: CREDIT
        sync: false
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
